[package]

name = "alfred"
version = "3.0.1"
authors = ["Kevin Ballard <kevin@sb.org>"]
description = """
A library for writing Alfred workflows.

http://www.alfredapp.com
"""

documentation = "http://www.rust-ci.org/kballard/alfred-rs/doc/alfred/"
repository = "https://github.com/kballard/alfred-rs"

readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]

serde_json = "1.0"
